# -*- coding: utf-8 -*-
"""Stock analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OzK7n4FaWzOTeQ5MnAwfWKxf686WRmtv
"""

# script1_data_fetch.py (Conceptual Python Code)

import pandas as pd
import datetime as dt
# Assuming a library like 'nselib' or 'yfinance' is installed
# If using pure scraping, replace this with 'requests' and 'BeautifulSoup'

def fetch_nifty50_data():
    """Fetches NIFTY 50 stocks list, sectors, and 5-day OHL-C data."""
    try:
        # Step 1: Fetch NIFTY 50 Symbols and Sectors (Do not hardcode)
        # --- Placeholder for list and sector fetching logic ---
        # Example using a placeholder dictionary (MUST be replaced with live scraping):
        nifty_stocks_list = [
            {'Symbol': 'RELIANCE', 'Sector': 'Oil & Gas'},
            {'Symbol': 'HDFCBANK', 'Sector': 'Private Banks'},
            # ... all 50 stocks
        ]

        # Step 2: Calculate date range (last 5 trading days)
        end_date = dt.date.today()
        # You'd need a more robust way to get 5 *trading* days,
        # but for a challenge, a simple offset can be a starting point.
        start_date = end_date - dt.timedelta(days=10) # Safe buffer for 5 trading days

        all_stocks_data = []
        for stock_info in nifty_stocks_list:
            symbol = stock_info['Symbol']
            sector = stock_info['Sector']

            try:
                # Step 3: Fetch historical data for the stock (placeholder for data library)
                # Example: Fetch daily data for symbol from start_date to end_date
                # data = fetch_historical_data(symbol, start_date, end_date)

                # --- Placeholder for fetched daily data for the last 5 days ---
                # A pandas DataFrame is ideal: [Date, Open, High, Low, Close]

                # Filter to the actual last 5 trading days and extract OHL-C
                # data = data.tail(5)

                # For simulation purposes:
                data = pd.DataFrame({
                    'Date': [end_date - dt.timedelta(days=i) for i in range(1, 6)],
                    'Open': [100.0, 101.0, 102.0, 103.0, 104.0],
                    'High': [102.0, 103.0, 104.0, 105.0, 106.0],
                    'Low': [99.0, 100.0, 101.0, 102.0, 103.0],
                    'Close': [101.5, 102.5, 103.5, 104.5, 105.5]
                })

                data['Symbol'] = symbol
                data['Sector'] = sector
                all_stocks_data.append(data)

            except Exception as e:
                print(f"Error fetching data for {symbol}: {e}")
                continue # Continue to the next stock on failure

        if not all_stocks_data:
            print("Failed to fetch data for any stock.")
            return

        final_df = pd.concat(all_stocks_data, ignore_index=True)
        # Step 4: Save data to a file for Script 2
        final_df.to_csv('nifty50_stock_data.csv', index=False)
        print("Data fetch successful. Saved to 'nifty50_stock_data.csv'")

    except Exception as e:
        print(f"Critical error in Script 1: {e}")

if __name__ == "__main__":
    fetch_nifty50_data()

# script2_analysis.py (Conceptual Python Code)

import pandas as pd

def analyze_and_output():
    """Loads data, performs momentum analysis, and prints the result."""
    try:
        # Step 1: Load data
        df = pd.read_csv('nifty50_stock_data.csv')

        # Step 2: Preprocess data
        df['Date'] = pd.to_datetime(df['Date']).dt.date
        df = df.sort_values(by=['Symbol', 'Date'])

        # Step 3: Calculate daily percentage change for each stock
        df['Prev_Close'] = df.groupby('Symbol')['Close'].shift(1)
        df.dropna(subset=['Prev_Close'], inplace=True) # Drop the first day of each stock's data
        df['Daily_Change_%'] = ((df['Close'] - df['Prev_Close']) / df['Prev_Close']) * 100

        # Step 4: Calculate average daily percentage change for each sector
        sector_momentum = df.groupby(['Date', 'Sector'])['Daily_Change_%'].mean().reset_index()

        # Step 5: Identify the sector with the highest momentum for each day
        highest_momentum_sectors = sector_momentum.loc[
            sector_momentum.groupby('Date')['Daily_Change_%'].idxmax()
        ].sort_values(by='Date', ascending=False)

        # Filter for only the last 5 unique trading days
        last_5_days = highest_momentum_sectors['Date'].unique()[:5]
        output_data = highest_momentum_sectors[highest_momentum_sectors['Date'].isin(last_5_days)]

        # Reverse the order to show Day 1, Day 2, etc. (chronological order)
        output_data = output_data.sort_values(by='Date', ascending=True).reset_index(drop=True)

        # Step 6: Print the output
        print("--- Sector Momentum Analysis ---")
        for i, row in output_data.iterrows():
            day_num = i + 1
            sector_name = row['Sector']
            avg_change = row['Daily_Change_%']
            print(f"Day {day_num}: {sector_name} ({avg_change:.2f}%)")

    except FileNotFoundError:
        print("Error: 'nifty50_stock_data.csv' not found. Please run Script 1 first.")
    except Exception as e:
        print(f"Critical error in Script 2: {e}")

if __name__ == "__main__":
    analyze_and_output()

